#!/usr/bin/env python3
# ansible/files/generate_logstash_pipeline.py
import sys
import xml.etree.ElementTree as ET
import re

if len(sys.argv) != 3:
    print("Usage: generate_logstash_pipeline.py <rules.xml> <out_logstash.conf>")
    sys.exit(2)

rules_path = sys.argv[1]
out_path = sys.argv[2]

tree = ET.parse(rules_path)
root = tree.getroot()

filters = []
for group in root.findall("group"):
    for rule in group.findall("rule"):
        sid = rule.get("id")
        desc = rule.findtext("description", default="")
        match = rule.findtext("match")
        regex = rule.findtext("regex")

        cond = None
        if match:
            pat = re.escape(match)
            cond = f"/{pat}/"
        elif regex:
            cond = f"/{regex}/"
        else:
            continue

        filters.append((sid, desc, cond))

with open(out_path, "w") as f:
    f.write("# Generated by generate_logstash_pipeline.py\n")
    f.write("input { tcp { port => 5000 codec => plain } }\n\n")
    f.write("filter {\n")
    for sid, desc, cond in filters:
        f.write(f"  if [message] =~ {cond} {{\n")
        f.write(f"    mutate {{ add_tag => [\"rule_{sid}\"] }}\n")
        f.write(f"    # {desc}\n")
        f.write("  }\n")
    f.write("}\n\n")
    f.write('output { elasticsearch { hosts => ["http://elasticsearch:9200"] } }\n')
