---

- name: Set container variables
  set_fact:
    image_full: "{{ item.ecr_repo_url }}:{{ item.image_tag | default('latest') }}"
    container_name: "{{ item.name }}"
    run_args: "{{ item.run_args | default('') }}"

- name: Login to AWS ECR
  shell: |
    aws ecr get-login-password --region eu-central-1 \
    | docker login --username AWS --password-stdin {{ item.ecr_repo_url.split('/')[0] }}
  args:
    executable: /bin/bash

- name: Pull Docker image
  shell: |
    docker pull {{ image_full }}
  args:
    executable: /bin/bash

- name: Stop container if already running
  shell: |
    docker rm -f {{ container_name }} || true
  args:
    executable: /bin/bash

- name: Run container
  shell: |
    docker run -d {{ run_args }} --name {{ container_name }} {{ image_full }}
  args:
    executable: /bin/bash
