pipeline {
  agent any

  environment {
    AWS_REGION = "eu-central-1"
    BUCKET_NAME = "thesamuraibucket"
    PAYLOAD_KEY = "payloads/input.json"
  }

  stages {
    stage('Fetch Payload') {
      steps {
        withAWS(credentials: 'mnasri', region: "${env.AWS_REGION}") {
          sh 'aws s3 cp s3://$BUCKET_NAME/$PAYLOAD_KEY ./payloads/sample.json'
        }
      }
    }

    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh 'terraform plan -out=tfplan'
      }
    }

    stage('Terraform Apply') {
      steps {
        sh 'terraform apply -auto-approve tfplan'
      }
    }
  }
}

